# Generated by Django 4.1.7 on 2023-04-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('admin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.admin')),
            ],
            bases=('accounts.admin',),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
