# Generated by Django 4.1.7 on 2023-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_group_g_teacher_alter_session_s_teacher'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='courses.course'),
        ),
    ]
