# Generated by Django 4.1.7 on 2023-04-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_courses_alter_teacher_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperUser',
        ),
    ]
