# Generated by Django 4.1.7 on 2023-04-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('s_description', models.TextField(blank=True, null=True)),
                ('s_courses', models.ManyToManyField(related_name='sessions', to='courses.course')),
                ('s_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='g_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_groups',
            field=models.ManyToManyField(related_name='courses', to='courses.group'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_levels',
            field=models.ManyToManyField(related_name='courses', to='courses.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_sessions',
            field=models.ManyToManyField(related_name='courses', to='courses.session'),
        ),
    ]
