# Generated by Django 4.1.7 on 2023-04-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_group_g_teacher_session_s_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='g_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='session',
            name='s_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
