# Generated by Django 4.1.7 on 2023-04-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_group_g_teacher_alter_session_s_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='courses.group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='c_sessions',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='courses.session'),
        ),
    ]
