# Generated by Django 4.1.7 on 2023-04-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_c_groups_alter_course_c_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='g_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.FloatField(),
        ),
    ]
