# Generated by Django 4.1.7 on 2023-04-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_courses_alter_teacher_courses'),
        ('courses', '0004_alter_course_c_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='group', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='g_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
