# Generated by Django 4.1.7 on 2023-04-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_group_name_alter_group_g_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='number',
        ),
    ]
