# Generated by Django 4.1.7 on 2023-04-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_number_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='number',
        ),
    ]
