# Generated by Django 4.1.7 on 2023-05-01 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_courses_alter_teacher_courses'),
        ('courses', '0006_remove_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='s_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
